baseURL = "https://content.iriss.org.uk/gypsy-traveller-intersectionality"
languageCode = "en-gb"
title = "Gypsy/Traveller intersectionality: strengthening the role of social work"
theme = ["hugo-notice", "iriss-course"]
verbose = true
copyrighthtml = "Copyright &#xA9; 2017 John Doe. All Rights Reserved."
menu = "main"
googleAnalytics = "UA-814723-1"
disableKinds = ["RSS", "taxonomy", "taxonomyTerm", "404"]
publishDir = "docs"
enableInlineShortcodes = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[social]
  twitter = "irissorg"

[params]
  description = "This resource explores the intersectionality of Gypsy/Traveller identity and provides valuable insight for social work professionals"
  images = ["images/tw-card.png"]
  IrissCourseAuthors  = "Davie Donaldson"
  IrissPublishDate = "June 2021"
  IrissCourseYearReleased = "2021"
  IrissHomeTitle = "Gypsy/Traveller intersectionality: strengthening the role of social work"
  IrissDescription = "This resource explores the intersectionality of Gypsy/Traveller identity and provides valuable insight for social work professionals"

[markup.tableOfContents]
  endLevel = 3

[privacy]
   [privacy.googleAnalytics]
    anonymizeIP = true
    disable = false
    respectDoNotTrack = true
    useSessionStorage = false
